language: go

go:
  - 1.14.x
  - master
  - tip

before_install:
  - go get github.com/pkg/errors
  - go get github.com/stretchr/testify
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
